baseURL = "/"
title = "Hugo owaraiclub theme"
theme= "hugo-owaraiclub"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 9

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.side]]
  identifier = "tags"
  name = "TAGS"
  url = "/tags"
  weight = 1

[[menu.side]]
  identifier = "CATEGORIES"
  name = "CATEGORIES"
  url = "/categories/"
  weight = 2

[[menu.side]]
  identifier = "AUTHORS"
  name = "AUTHORS"
  url = "/author/"
  weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "author"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

